package com.example.shared.domain.entity

object NotificationTypes {
    const val REQUEST_ACCEPTED = "REQUEST_ACCEPTED"
    const val PAYMENT_PENDING = "PAYMENT_PENDING"
    const val REQUEST_REJECTED = "REQUEST_REJECTED"
    const val PAYMENT_ISSUE = "PAYMENT_ISSUE"
    const val PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    const val APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    const val APPOINTMENT_REMINDER_24H = "APPOINTMENT_REMINDER_24H"
    const val APPOINTMENT_REMINDER_2H = "APPOINTMENT_REMINDER_2H"
    const val APPOINTMENT_STARTED = "APPOINTMENT_STARTED"
    const val APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED"
    const val REVIEW_PENDING_CLIENT = "REVIEW_PENDING_CLIENT"
    const val REVIEW_PENDING_WORKER = "REVIEW_PENDING_WORKER"
    const val APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    const val NEW_REQUEST_RECEIVED = "NEW_REQUEST_RECEIVED"
    const val PAYMENT_RECEIPT_UPLOADED = "PAYMENT_RECEIPT_UPLOADED"
    const val REVIEW_RECEIVED = "REVIEW_RECEIVED"
    const val REVIEW_SUBMITTED_SUCCESS = "REVIEW_SUBMITTED_SUCCESS"
}